export const ROLES = {
    ADMIN: "ADMIN",
    SUBADMIN: "SUBADMIN",
    USER: "USER",
    SALESTEAM: "SALESTEAM",
    WAREHOUSE: "WAREHOUSE",
    MANAGEMENT: "MANAGEMENT",
    RECEPTIONIST: "RECEPTIONIST",
    BILLING: "BILLING",
    CASHIER: "CASHIER",
    SECURITY: "SECURITY",
};

export const ROLES_CONSTANT_USER = {
    USER: "USER",
    WHOLESALER: "WHOLESALER",
    RETAILER: "RETAILER",
    SHOPKEEPER: "SHOPKEEPER",
  };
  
export  const APPROVED_STATUS = {
    APPROVED :"APPROVED",
    PENDING :"PENDING",
    REJECTED :"REJECTED",
}

export const ROLES_TYPE = {
    SUBADMIN: "SUBADMIN",
    CUSTOMER: "CUSTOMER",
  };
  