export const ROLES = {
  ADMIN: "ADMIN",
  SUBADMIN: "SUBADMIN",
  USER: "USER",
  SALESTEAM: "SALESTEAM",
  WAREHOUSE: "WAREHOUSE",
  MANAGEMENT: "MANAGEMENT",
  RECEPTIONIST: "RECEPTIONIST",
  BILLING: "BILLING",
  CASHIER: "CASHIER",
  SECURITY: "SECURITY",
} as const;

export type ROLES_TYPE = keyof typeof ROLES;
